version: '3.3'

services:
  bank-transmitter-consent-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bank-transmitter-consent-db'
      MYSQL_USER: 'bank-transmitter-consent-db-user'
      MYSQL_PASSWORD: 'bank-transmitter-consent-db-pass'
      MYSQL_ROOT_PASSWORD: 'bank-transmitter-consent-db-pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ~/bank-transmitter-consent-db-volume:/var/lib/mysql

  bank-receiver-consent-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'bank-receiver-consent-db'
      MYSQL_USER: 'bank-receiver-consent-db-user'
      MYSQL_PASSWORD: 'bank-receiver-consent-db-pass'
      MYSQL_ROOT_PASSWORD: 'bank-receiver-consent-db-pass'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - ~/bank-receiver-consent-db-volume:/var/lib/mysql

  rabbitmq:
         image: rabbitmq:3-management
         container_name: rabbitmq_management
         
         ports: 
          - 25672:25672 # (erlang) communication between the nodes and CLI tool
          - 15673:15672 # communication with the web management API 
          - 5673:5672 # communication with the web management API 
         expose:
          - '5673'
         volumes:
          - ~/bank-receiver-rabbitmq:/var/lib/rabbitmq/
         environment:
          - RABBITMQ_DEFAULT_USER = guest
          - RABBITMQ_DEFAULT_PASS = guest
         restart: always

# Names our volume
volumes:
  bank-transmitter-consent-db-volume:
    driver: local
  bank-receiver-consent-db-volume:
    driver: local
  rabbitmq-volume:
    driver: local