trigger:
- master
- main
- pipeline

pool:
  vmImage: ubuntu-latest
steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- task: CmdLine@2
  displayName: 'Directory listing'
  inputs:
    script: |
      cd $(Agent.BuildDirectory)
      ls -Rla

- script: |
    npm install --location=global @angular/cli
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
      app_location: "/"
      api_location: ""
      output_location: "dist/apps/bank-receiver-consumer"
  env:
      azure_static_web_apps_api_token: $(deployment_token)